version: "3.8"

services:
  lavalink:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-0.0.0.0}
      - SERVER_HTTP2_ENABLED=${SERVER_HTTP2_ENABLED:-false}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD:-youshallnotpass}
    volumes:
      - lavalink-logs:/app/logs/
      - lavalink-plugins:/app/plugins/
      - type: bind
        source: ./volumes/lavalink/application.yml
        target: /app/application.yml
    restart: unless-stopped
volumes:
  lavalink-logs:
  lavalink-plugins:
