version: "3.8"
services:
  lavalink:
    image: lavalink
    build: .
    ports:
      - "2333:2333"
    volumes:
      - lavalink-data:/app/logs/
      -
        type: bind
        source: ./volumes/lavalink/application.yml
        target: /app/application.yml
        content: ""
    restart: unless-stopped
