version: "3.8"

services:
  lavalink:
    build: .
    volumes:
      - lavalink-data:/app/logs/
      - type: bind
        source: ./volumes/lavalink/application.yml
        target: /app/application.yml
    restart: unless-stopped
volumes:
  lavalink-data:
