version: "3.8"
services:
  lavalink:
    image: lavalink
    build: .
    ports:
      - "2333:2333"
    volumes:
      - lavalink-data:/app/logs/
      - lavalink-application.yml:/app/application.yml
    restart: unless-stopped
